---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: tomctm/golang-app:1.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "yYTiTR66EG"
        - name: POSTGRES_DB
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgresql"
        - name: DATABASE_PORT
          value: "5432"
